name: lmi-for-A13
on:
  workflow_dispatch:
    inputs:
      URL:
        description: "待操作的系统包下载地址"
        required: true
      custom_version:
        description: "待打包的版本号"
      one:
        description: "123pan上传"
        default: '0'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 克隆
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PASSNAME }}
          repository: Meetingfate/action_build_lmi_rom_A13
      - name: 制作rom‌‌
        run: |
          sudo bash "$GITHUB_WORKSPACE"/make.sh lmi ${{ github.event.inputs.URL }} ${{ github.event.inputs.custom_version }} $GITHUB_WORKSPACE ${{ secrets.PASSWORD }} ${{ github.event.inputs.one }}
      - name: 删除工作流运行
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0
