name: Release
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        run: |
          # build your project here
          
      - name: Create release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.PASSNAME }}
        with:
          tag_name: test
          release_name: test2023
          body: |
            test6.6
          draft: false
          prerelease: false
      - name: Upload asset
        uses: actions/upload-artifact@v2.2.4
        env:
          GITHUB_TOKEN: ${{ secrets.PASSNAME }}
        with:
          name: action_build_lmi_rom_A13
          path: ${{ github.workspace }}/*
